[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[dev]
  command = "npm run dev:client"
  targetPort = 5173
  publish = "dist"
